config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'parents#index'
  resources :tweets do
    resources :comments, only: [:create]
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show]
  resources :parents, only: [:show]
  resources "parents", path:'parents/:id'
  resources :parents, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tweet, counter_cache: :comments_count     #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_one :tweet
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  mount_uploader :image, PhraseImageUploader
  has_many :tweets, through: :tweet_phrases
  has_many :tweet_phrases

  accepts_nested_attributes_for :tweets
  enum phrase_type: [:subject, :object, :verb, :impression]
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :phrases, through: :tweet_phrases
  has_many :tweet_phrases, dependent: :destroy
  has_many :comments           #commentsテーブルとのアソシエーション
  belongs_to :image
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :tweet_phrases, allow_destroy: true

  def created_at
    self['created_at'].to_s(:date)
  end

  def phrase_type_and_text
    self.phrases.map{|p| [p.phrase_type,p.text]}.to_h
  end

  def like_user(user_id)
    self.likes.find_by(user_id: user_id)
  end
end

app/models/tweet_phrase.rb
class TweetPhrase < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :phrase
  
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :comments               #commentsテーブルとのアソシエーション
  has_many :images                 #imagesテーブルとのアソシエーション

  def newer_images
	self.images.order("created_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{@comment.tweet.id}"   #コメントと結びつくツイートの詳細画面に遷移する
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet ,only: [:create, :destroy]
  
  def create
    @tweet.likes.create(user_id: current_user.id)
  end

  def destroy
    like = @tweet.likes.find_by(user_id: current_user.id)
    like.destroy
    @tweet.reload
  end
  
  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

  def index
  end

  def show
    if current_user.id == params[:id].to_i
      @user = current_user
    else
      redirect_to root_path
    end
  end

  def create
    current_user.images.create(image_params)
    redirect_to parent_path
  end

  private
  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index, :show]
  before_action :set_all_phrases, only: [:new, :edit]
  before_action :set_tweet, only: [:destroy, :edit, :update, :show]

  def index
    @tweets = Tweet.includes(:user, :image, :phrases).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
    @tweet.tweet_phrases.build
    @sample_phrases = { subject: "ぼくは", object: "がっこうに", verb: "いった", impression: "たのしかった" }
    @current_date = DateTime.now.to_s(:date)
  end

  def create
    tweet = current_user.tweets.create(tweet_params)
  end

  def destroy
    if @tweet.user_id == current_user.id
      @tweet.destroy
    end
  end

  def edit
  end

  def update
    if @tweet.user_id == current_user.id
      @tweet.tweet_phrases.each do |phrase|
        phrase.destroy
      end
      @tweet.update(tweet_params)
    end
  end

  def show
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image_id, tweet_phrases_attributes: [:phrase_id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_all_phrases
    @phrases = Phrase.all
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.includes(:image, :phrases).page(params[:page]).per(5).order("created_at DESC")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>なつの絵にっき</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <%= link_to root_path, class: "navbar-name font-weight-bold" do %>なつの絵にっき
        <% end %>
        <% if user_signed_in? %>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "絵にっきをかく", new_tweet_path, class: " nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "みんなの絵にっきを見る", tweets_path, class: " nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to "#{current_user.nickname}の絵にっきを見る", user_path(current_user) , class: " nav-link" %>
              </li>
              <li class="nav-item" id="parent_btn">
                <%= link_to "保護者用ページへ", parent_path(current_user), class: " nav-link" %>
              </li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>
    <%= yield %>
    <footer class="text-center text-muted py-3 my-3 bg-light"><p>Copyright 2018 Team Enikki All Rights Reserved.</p></footer>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if tweet.like_user(current_user.id) %>
    <%= button_to tweet_likes_path(likes, tweet_id: tweet.id), method: :delete, id: "like-button-#{tweet.id}", class: "like_button", remote: true do %>
      <%= image_tag("icon_red_heart.png", class: "like_image") %>
      <span>
        <%= tweet.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to tweet_likes_path(tweet), id: "like-button-#{tweet.id}", class: "like_button", remote: true do %>
      <%= image_tag("icon_heart.png", class: "like_image") %>
      <span>
        <%= tweet.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= image_tag("icon_heart.png", class: "like_image") %>
    <span>
      <%= tweet.likes_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("#like-button-<%= @tweet.id %>").html("<%= j(render partial: 'like', locals: { tweet: @tweet, likes: @tweet.likes}) %>")

app/views/likes/destroy.js.erb
$("#like-button-<%= @tweet.id %>").html("<%= j(render partial: 'like', locals: { tweet: @tweet, likes: @tweet.likes }) %>");

app/views/parents/index.html.erb
<div class="container">
  <div class="m-3 p-1">
    <h1 class="text-center font-weight-bold">なつの絵にっき</h1>
    <%= image_tag "oekaki.png", class: "center-block main_img" %>
  </div>
  <% if user_signed_in? %>
    <div class="d-flex flex-column align-items-center flex-sm-row justify-content-around">
      <%= link_to new_tweet_path, class: 'btn btn-primary mx-4 d-inline-block main_btn my-2' do %>
        <h4 class="text-center">絵にっきをかく</h4>
      <% end %>
      <%= link_to tweets_path, class: 'btn btn-primary mx-4 d-inline-block main_btn my-2' do %>
        <h4 class="text-center">みんなの絵にっきを見る</h4>
      <% end %>
      <%= link_to user_path(current_user), class: 'btn btn-primary mx-4 d-inline-block main_btn my-2' do%>
        <h4 class="text-center"><%= "#{current_user.nickname}の絵にっきを見る" %></h4>
      <% end %>
    </div>
  <% else %>
    <%= link_to "ログイン", new_user_session_path, method: 'post', class: 'btn'%>
    <%= link_to "新規登録", new_user_registration_path, method: 'post', class: 'btn'%>
  <% end %>
</div>

app/views/parents/show.html.erb
<div class="container">
  <div class="m-3 p-1">
    <h1 class="text-center font-weight-bold">保護者用ページ</h1>
    <div class="success">
      <h3 class="text-center">アカウント関連</h3>
      <div class="d-flex flex-column align-items-center flex-sm-row justify-content-around">
        <%= link_to edit_user_registration_path(@user), class: 'btn btn-primary btn-block mt-2 mx-1 d-inline-block main_btn' do %>
          <h4>アカウント編集</h4>
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-block mt-2 mx-1 d-inline-block main_btn' do %>
          <h4>ログアウト</h4>
        <% end %>
      </div>
    </div>
    <div class="success">
      <h3 class="text-center">絵にっき画像追加</h3>
      <%= form_for :image do |f| %>
        <div class="form-inline p-2 text-center">
          <%= f.file_field :image, class: "btn btn-outline-light col border border-dark" %>
          <%= f.submit "送信", class: "btn btn-primary" %>
        </div>
      <% end %>
      <div class="m-2 p-2">
        <h3 class="text-center">絵にっき画像一覧</h3>
        <% @user.newer_images.each do |img| %>
          <%= content_tag :div, nil,class: "prepared_image col-sm-3 thumbnail", style: "background-image:url(#{img.image.url})" do %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet mb-3 pt-5 pb-3 border-bottom d-flex flex-column align-items-center">
  <div class="tweet_content d-flex flex-column align-items-center flex-sm-row">
    <div class="contents_body mx-3 my-2">
      <div class= "user_avatar rounded-circle" style="background-image: url(<%= tweet.user.avatar %>);">
        <span class= "user_name"><%= tweet.user.nickname %></span>
      </div>
      <div class="content_text">
        <div class="text_date h-25">
          <%= content_tag :h4, tweet.created_at%>
        </div>
        <div class="text_body d-flex flex-column justify-content-center text-center h-75 ml-3">
          <% tweet.phrase_type_and_text.each do |phrase_type, text| %>
            <%= content_tag :div, text, class: "form_type_btn #{phrase_type} rounded", id: "#{phrase_type}_btn"%>
          <% end %>
          <div class="content_text__polygon"></div>
        </div>
      </div>
    </div>
    <%= content_tag :div, class: "content_image p-3 mx-3 my-2", style:("background-image: url( #{tweet.image.image});" if tweet.image) do%>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <div class="more float-right">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
          <ul class="dropdown-menu">
            <li class="dropdown-menu-item"><%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %></li>
            <li class="dropdown-menu-item"><%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %></li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class= "tweet_reactions d-flex justify-content-around">
    <%= render partial: 'likes/like', locals: { tweet: tweet, likes: @likes} %>
    <%= button_to tweet_path(tweet), class: "comment_icon", method: :get do %>
      <%= fa_icon "comments", class: "fa-3x" %>
      <span><%= tweet.comments_count %></span>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet_comment.html.erb
<div class="comments d-flex flex-column align-items-center">
  <% if current_user %>
    <%= form_tag tweet_comments_path(tweet), method: :post do %>
      <div class="p-3 d-flex flex-column align-items-center flex-md-row">
        <textarea name="text" class="form-control" placeholder="コメントする"></textarea>
        <input type="submit" value="コメントをおくる" class="btn btn-primary m-2">
      </div>
    <% end %>
  <% end %>
  <h4>＜みんなのコメント＞</h4>
  <% if comments %>
    <% comments.each do |comment| %>
      <p class="w-100">
        <strong><%= link_to comment.user.nickname, user_path(comment.user) %>：</strong>
        <%= comment.text %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/tweets/_tweet_form.html.erb
<div class="tweet_content">
  <div class= "user_avatar" style="background-image: url(<%= current_user.avatar %>);">
    <span class= "user_name"> <%= current_user.nickname %></span>
  </div>
  <div class="content_text">
    <div class="text_date">
      <%= content_tag :span, time%>
    </div>
    <div class="text_body post">
      <% phrases.each do |phrase_type, text| %>
        <%= content_tag :div, text, class: "form_type_btn #{phrase_type}", id: "#{phrase_type}_btn"%>
      <% end %>
    </div>
    <div class="content_text__polygon"></div>
  </div>
  <%= content_tag :div, nil, class: ["form_type_btn", "image", "content_image"], id: "image_btn", style: ("background-image: url(#{tweet.image.image});" if tweet.image) do%>
    <%= content_tag :h3, "あたらしく かいた　絵" unless tweet.image%>
  <% end %>

</div>

<div class= "tweet_forms row">
  <%= form_for(@tweet) do |f|%>
    <% Phrase.phrase_types.each_pair do |phrase_type, phrase_type_id|%>
      <%= f.fields_for :tweet_phrases do |tweet_phrase| %>
        <div class="form_items <%= phrase_type %> row" id= "<%= phrase_type %>_items" >
          <% @phrases.where(phrase_type: phrase_type_id).each do |item| %>
            <%= tweet_phrase.label "phrase_id_#{item.id}", class: "form_item col-md-4 col-sm-6 col-xs-6 thumbnail" do %>
              <%= tweet_phrase.radio_button :phrase_id, item.id, class: "phrase_input"%>
              <%= item.text %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= f.hidden_field :_destroy , value: true%>
    <div class="form_items image row" id="image_items">
      <%= fields_for :image do |image| %>
        <% if current_user.newer_images.present? %>
          <% current_user.newer_images.each do |img| %>
            <%= label_tag :image_id, "",for: "image_id_#{img.id}", class: "form_item image col-md-4 col-sm-6 col-xs-6 thumbnail", style: "background-image:url(#{img.image.url})" do %>
              <%= radio_button_tag :image_id, img.id , nil, class: "phrase_input"%>
            <% end %>
          <% end %>
        <% else %>
          <div class="alert alert-warning" role="alert">画像が登録されていません！</div>
        <% end %>
      <% end %>
    </div>
    <%= f.submit value: "お友だちにみせよう" %>
  <% end %>
</div>

app/views/tweets/_tweet_form_edit.html.erb
<div class="container">
  <div class="alert alert-info my-3 text-center">
    言葉や画像を選んで、絵にっきを書きかえよう！
  </div>
  <div class="tweet mb-3 py-4 d-flex flex-column align-items-center">
    <div class="tweet_content d-flex flex-column align-items-center flex-sm-row">
      <div class="contents_body mx-3 my-2">
        <div class= "user_avatar rounded-circle" style="background-image: url(<%= current_user.avatar %>);">
          <span class= "user_name"><%= current_user.nickname %></span>
        </div>
        <div class="content_text">
          <div class="text_date h-25">
            <%= content_tag :h4, tweet.created_at%>
          </div>
          <div class="text_body d-flex flex-column justify-content-center text-center text-secondary h-75 ml-3 post">
            <% tweet.phrase_type_and_text.each do |phrase_type, text| %>
              <%= content_tag :div, text, class: "form_type_btn #{phrase_type} rounded", id: "#{phrase_type}_btn"%>
            <% end %>
            <div class="content_text__polygon"></div>
          </div>
        </div>
      </div>
      <%= content_tag :div, class: "form_type_btn  image content_image p-3 mx-3 my-2 d-flex align-items-center text-secondary", id: "image_btn", style: ("background-image: url(#{tweet.image.image});" if tweet.image) do%>
        <%= content_tag :h3, "あたらしく かいた絵", class: "m-auto" unless tweet.image%>
      <% end %>
    </div>
  </div>
  <div class= "tweet_forms">
    <%= form_for(@tweet) do |f| %>
      <% Phrase.phrase_types.each_pair do |phrase_type, phrase_type_id|%>
        <%= f.fields_for :tweet_phrases, @tweet.tweet_phrases, include_id: false do |tweet_phrase| %>
          <% phrase_type_id = tweet_phrase.index %>
          <% phrase_type = Phrase.phrase_types.key(phrase_type_id) %>
          <div class="form_items <%= phrase_type %> row" id= "<%= phrase_type %>_items" >
            <% @phrases.where(phrase_type: phrase_type_id).each do |item| %>
              <%= tweet_phrase.label "phrase_id_#{item.id}", class: "form_item col-sm-3 thumbnail", style: "background-image: url(#{item.image});" do %>
                <%= tweet_phrase.radio_button :phrase_id, item.id, class: "phrase_input"%>
                <%= content_tag :p, item.text %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div class="form_items image" id="image_items">
        <%= fields_for :image do |image| %>
          <% if current_user.newer_images.present? %>
            <% current_user.newer_images.each do |img| %>
              <%= f.label :image_id, "",for: "tweet_image_id_#{img.id}", class: "form_item image col-sm-3 thumbnail", style: "background-image:url(#{img.image.url})" do %>
                <%= f.radio_button :image_id, img.id, class: "phrase_input"%>
              <% end %>
            <% end %>
          <% else %>
            <div class="alert alert-warning text-center" role="alert">
              <span>画像を登録しよう！ <br></span>
              <%= link_to "画像追加フォームはこちら",parent_path(current_user)%>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= f.submit value: "お友だちにみせよう", class: "btn btn-primary btn-block btn_submit" %>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet_form_new.html.erb
<div class="container">
  <div class="alert alert-info my-3 text-center">
    言葉や画像をすべて選んで、絵にっきを完成させよう！
  </div>
  <div class="tweet mb-3 py-4 d-flex flex-column align-items-center">
    <div class="tweet_content d-flex flex-column align-items-center flex-sm-row">
      <div class="contents_body mx-3 my-2">
        <div class= "user_avatar rounded-circle" style="background-image: url(<%= current_user.avatar %>);">
          <span class= "user_name"> <%= current_user.nickname %></span>
        </div>
        <div class="content_text">
          <div class="text_date h-25">
            <%= content_tag :h4, time%>
          </div>
          <div class="text_body d-flex flex-column justify-content-center text-center text-secondary h-75 ml-3 post">
            <% phrases.each do |phrase_type, text| %>
              <%= content_tag :div, text, class: "form_type_btn #{phrase_type} rounded", id: "#{phrase_type}_btn"%>
            <% end %>
            <div class="content_text__polygon"></div>
          </div>
        </div>
      </div>
      <%= content_tag :div, class: "form_type_btn image content_image p-3 mx-3 my-2 d-flex align-items-center text-secondary", id: "image_btn", style: ("background-image: url(#{tweet.image.image});" if tweet.image) do%>
        <div class="content_text__polygon"></div>
        <%= content_tag :h3, "あたらしく かいた絵", class: "m-auto"  unless tweet.image%>
      <% end %>
    </div>
  </div>
  <div class= "tweet_forms">
    <%= form_for(@tweet) do |f| %>
      <% Phrase.phrase_types.each_pair do |phrase_type, phrase_type_id|%>
        <%= f.fields_for :tweet_phrases, @tweet.tweet_phrases, include_id: false do |tweet_phrase| %>
          <div class="form_items <%= phrase_type %>" id= "<%= phrase_type %>_items">
            <% @phrases.where(phrase_type: phrase_type_id).each do |item| %>
              <%= tweet_phrase.label "phrase_id_#{item.id}", class: "form_item thumbnail m-2", style: "background-image: url(#{item.image});" do %>
                <%= tweet_phrase.radio_button :phrase_id, item.id, class: "phrase_input"%>
                <%= content_tag :p, item.text %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div class="form_items image" id="image_items">
        <%= fields_for :image do |image| %>
          <% if current_user.newer_images.present? %>
            <% current_user.newer_images.each do |img| %>
              <%= f.label :image_id, "",for: "tweet_image_id_#{img.id}", class: "form_item image thumbnail m-2", style: "background-image:url(#{img.image.url})" do %>
                <%= f.radio_button :image_id, img.id, class: "phrase_input"%>
              <% end %>
            <% end %>
          <% else %>
            <div class="alert alert-warning text-center" role="alert">
              <span>画像を登録しよう！ <br></span>
              <%= link_to "画像追加フォームはこちら",parent_path(current_user)%>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= f.submit value: "お友だちにみせよう", class: "btn btn-primary btn-lg btn-block btn_submit m-3" %>
    <% end %>
  </div>
</div>

app/views/tweets/create.html.erb
<div class="container">
  <div class="success">
    <h3>絵にっきが完成したよ！</h3>
    <a class="btn" href="/tweets">いままでの絵にっきをみてみよう！</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="container">
  <div class="success">
    <h3>絵にっきをけしたよ！</h3>
    <a class="btn" href="/tweets">いままでの絵にっきをみてみよう！</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <h1 class="text-center font-weight-bold">絵にっきをかきなおす</h1>
  <%= render partial: "tweet_form_edit", locals: {
  	tweet: @tweet,
  	phrases: @tweet.phrase_type_and_text,
  	time: @tweet.created_at
  }%>
</div>

app/views/tweets/index.html.erb
<div class="container" >
  <h1 class="text-center font-weight-bold mb-5">みんなの絵にっき</h1>
  <% @tweets.each do |tweet| %>
    <%= render(tweet) %>
  <% end %>
  <div class="text-center"><%= paginate(@tweets) %></div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h1 class="text-center font-weight-bold">絵にっきをかく</h1>
  <%= render partial: "tweet_form_new", locals: {
    tweet: @tweet,
    phrases: @sample_phrases,
    time: @current_date
  }%>
</div>

app/views/tweets/show.html.erb
<div class="container" >
  <%= render @tweet %>
  <%= render partial: "tweet_comment", locals: {tweet: @tweet, comments: @comments}%>
</div>

app/views/tweets/update.html.erb
<div class="container">
  <div class="success">
    <h3>絵にっきを修正したよ！</h3>
    <a class="btn" href="/tweets">いままでの絵にっきをみてみよう！</a>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center font-weight-bold"><%= @nickname %>の絵にっき</h1>
  <div>
    <% @tweets.each do |tweet| %>
      <%= render(tweet) %>
    <% end %>
    <div class="text-center"><%= paginate(@tweets) %></div>
  </div>
</div>